# Define profile model
#
# * A profile defines a collection of levels in a game.
# * A game includes one or more levels.
# * A game has one or more end-game levels.
# * A game has one and only one begin-game level.
# * A level has one and only one entry.
# * A level has one or more exits. Each exit leads to
#   one and only one "next level".
# * A level can offer one or more "skills" after passing through.
#   For example, a BOSS fight level grants a new skill.
# * A level can require one or more skills to enter.
#
# * "" is a speical value because toml does not allow empty array.
#   It's not processed in lpath.

[lpath]
skills = ["pan", "glide", "fireball"]

    [[levels]]
    id = "1-1"
    description = "outside-castle"
    begin = true
    next-level = { "1-2" = [""], "2-1" = ["pan"] }

    [[levels]]
    id = "1-2"
    description = "castle-gate"
    next-level = { "bossfight-skeleton" = [""] }

    [[levels]]
    id = "bossfight-skeleton"
    unlock-skills = [ "pan" ]
    next-level = { "1-2" = [""] }

    [[levels]]
    id = "2-1"
    end = true
