# Define profile model
#
# * A profile defines a collection of stages in a game.
# * A game includes one or more stages.
# * A game has one or more end-game stages.
# * A game has one and only one begin-game stage.
# * A stage has one and only one entry.
# * A stage has one or more exits. Each exit leads to
#   one and only one "next stage".
# * A stage can offer one or more "skills" after passing through.
#   For example, a BOSS fight stage grants a new skill.
# * A stage can require one or more skills to enter.
#
# * "" is a speical value because toml does not allow empty array.
#   It's not processed in lpath.

[lpath]
skills = ["pan", "glide", "fireball"]

    [[stages]]
    id = "1-1"
    description = "outside-castle"
    begin = true
    # With 2-2 here, the path from bossfight1 back to 1-1 is not
    # considered as a loop.
    next-stage = { "1-2" = [""], "2-2" = ["pan"] }

    [[stages]]
    id = "1-2"
    description = "castle-gate"
    next-stage = { "bossfight1" = [""] }

    [[stages]]
    id = "bossfight1"
    unlock-skills = [ "pan" ]
    next-stage = { "2-1" = [""], "1-1" = [""] }

    [[stages]]
    id = "2-1"
    next-stage = { "2-2" = [""], "2-3" = ["pan"], "2-4" = ["fireball"] }

    [[stages]]
    id = "2-2"
    end = true

    [[stages]]
    id = "2-3"
    next-stage = { "2-5" = ["glide"] }

    [[stages]]
    id = "2-4" # Unreachable due to skill unmatch in 2-1
    end = true

    [[stages]]
    id = "2-5" # Unreachable (2-3 is deadend)
    end = true
